version: "3.4"
services:
    api:
      image: docker-testproject
      ports:
      - "4000:4000"
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        WAIT_HOSTS: database:5432
      depends_on: 
        - "database"
      

    database:
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/home/lib/postgresql/data
      environment:
        - POSTGRES_USER=dima
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=dima

      

volumes:
  pgdata:        



        
     
      