package main

// @title          Swagger Example API
// @version        1.0
// @description    This is a sample server celler server.
// @termsOfService http://swagger.io/terms/

// @contact.name  API Support
// @contact.url   http://www.swagger.io/support
// @contact.email support@swagger.io

// @host     localhost:4000
// @BasePath /
import (
	"log"
	"net/http"

	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/PeepoFrog/testProject/docs"
	"github.com/PeepoFrog/testProject/internal/router"
)

func main() {
	r := router.Router()
	srv := &http.Server{
		Addr:    "0.0.0.0:4000",
		Handler: r, //
	}
	if err := srv.ListenAndServe(); err != nil {
		log.Println(err)
	}
}
